name: tubextend_api
description: A set of functions required for the TubeXtend app
version: 0.0.1

homepage: https://tubextend.com
repository: https://github.com/rozentia/tubextend

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dart_openai: ^4.0.0
  envied: ^0.3.0+3
  flutter:
    sdk: flutter
  googleapis: ^11.4.0
  http: ^1.1.0
  logger: ^2.0.2+1
  youtube_explode_dart: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  test: ^1.24.3

flutter: null
