import 'package:youtube_explode_dart/youtube_explode_dart.dart';

import 'core/logger.dart';

/// Retrieves the transcript of a YouTube video with the given [videoId].
///
/// The transcript is retrieved using the [YoutubeExplode] package.
/// If no captions are found for the video, an [Exception] is thrown.
///
/// Example usage:
/// ```dart
/// String? transcript = await getVideoTranscript('VIDEO_ID_HERE');
/// if (transcript != null) {
///   print(transcript);
/// } else {
///   print('Failed to retrieve transcript');
/// }
/// ```
///
/// Returns a [Future] that completes with the transcript as a [String] if successful, or `null` if an error occurs.
///
/// Throws an [Exception] if no captions are found for the video.
Future<String?> getVideoTranscript(String videoId) async {
  final yt = YoutubeExplode();
  try {
    final manifest = await yt.videos.closedCaptions.getManifest(VideoId(videoId));
    final trackInfo = manifest.getByLanguage('en', autoGenerated: true);

    if (trackInfo.isNotEmpty != true) throw Exception('No captions found');
    final track = await yt.videos.closedCaptions.get(trackInfo.first);
    final data = track.captions.map((element) => element.text).join('\n');
    logger.i('Transcript fetched successfully');
    return data;
  } catch (e) {
    logger.e(e);
    rethrow;
  }
}
